# for local testing purposes

version: '3.8'

services:
  terra-back:
    container_name: terra-backend-test
    build:
      context: ./terra-back
      dockerfile: ./Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=azure
      - DB_URL=jdbc:postgresql://terra-db-test:5432/terra-db-test
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    ports:
      - "8080:8080"
    restart: unless-stopped
    networks:
      - terra_network

  terra-db-test:
    container_name: terra-db-test
    image: postgres:16
    environment:
      POSTGRES_DB: terra-db-test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - terra_network
  
  terra-front-test:
    container_name: terra-frontend-test
    build:
      context: ./terra-front
      dockerfile: ./Dockerfile
    environment:
      - REACT_APP_API_URL=http://localhost:8080/api/v1/terra
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - terra_network

networks:
  terra_network:
    driver: bridge
